name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./Microviz
    - name: Build
      run: dotnet build ./Microviz --no-restore
    - name: Test
      run: dotnet test ./Microviz --no-build --verbosity normal
    - name: Publish
      run: dotnet publish ./Microviz
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: my-artifact
       path: "./Microviz/"  

