name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore ./Microviz
    - name: Build
      run: dotnet build ./Microviz --configuration Release
    - name: Test
      run: dotnet test ./Microviz --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish ./Microviz --configuration Release -r ubuntu-x64 --self-contained
    - name: Upload Microviz Artifact
      uses: actions/upload-artifact@v2
      with:
        name: Microviz
        path: /home/runner/work/Microviz/Microviz/Microviz/bin/Release/net6.0/publish/
    

